spring:
  datasource:
    url: jdbc:mysql://localhost:3333/student_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
